trabalho_py/to_do_list/to_do_list/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'), #esta é a rota principal
    path('add', views.add, name='add'), #esta é a rota para adicionar uma tarefa
    path('edit_task/<int:task_id>/', views.edit_task, name='edit_task'), #esta é a rota para atualizar uma tarefa
    path('update_task/<int:task_id>/', views.update_task, name='update_task'), #esta é a rota para atualizar uma tarefa
    path('delete_task/<int:task_id>/', views.delete_task, name='delete_task'), #esta é a rota para deletar uma tarefa
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout, name='logout'),  # Atualize esta linha
    path('register/', views.register, name='register'), #esta é a rota para registrar um novo usuário
]

trabalho_py/to_do_list/app/models.py
from django.db import models
from django.contrib.auth.models import User

class Tasks(models.Model):
    id_task = models.AutoField(primary_key=True) #chave primária
    title_task = models.CharField(max_length=200) #título da tarefa
    description_task = models.TextField() #descrição da tarefa
    complete_task = models.CharField(max_length=10, choices=[('1', 'Pendente'), ('2', 'Em andamento'), ('3', 'Concluída')], default='1') #tarefa completada
    prazo_task = models.DateTimeField()  #prazo da tarefa
    priority_task = models.CharField(max_length=10, choices=[('3', 'Alta'), ('2', 'Média'), ('1', 'Baixa')], default='1') #prioridade da tarefa
    user = models.ForeignKey(User, on_delete=models.CASCADE) #usuário que criou a tarefa

trabalho_py/to_do_list/app/views.py
from django.shortcuts import render, redirect
from app.models import Tasks
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

def register(request): #registrar novo usuário
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})

#def home pronta até q enfim bagulho é o seguinte se o usuário for superuser ele pode ver todas as tarefas se não ele só pode ver as tarefas dele
#todas as linhas comentadas pra facilitar o entendimento
@login_required
def home(request):
    # Obtém o filtro de status da solicitação GET
    status_filter = request.GET.get('status')
    # Obtém o filtro de usuário da solicitação GET
    user_filter = request.GET.get('user')
    
    # Verifica se o usuário logado é um superusuário (administrador)
    if request.user.is_superuser:
        # Se for administrador, obtém todas as tarefas
        tasks = Tasks.objects.all()
        # Obtém todos os usuários para o filtro de usuário
        users = User.objects.all()
        # Aplica o filtro de usuário, se fornecido
        if user_filter:
            tasks = tasks.filter(user_id=user_filter)
    else:
        # Se não for administrador, obtém apenas as tarefas do usuário logado
        tasks = Tasks.objects.filter(user=request.user)
    
    # Aplica o filtro de status, se fornecido
    if status_filter:
        tasks = tasks.filter(complete_task=status_filter)
    
    # Ordena as tarefas por prioridade (decrescente) e prazo (crescente)
    tasks = tasks.order_by('-priority_task', 'prazo_task')
    
    # Cria o contexto a ser passado para o template
    context = {
        'tasks': tasks,
    }
    
    # Se o usuário for administrador, adiciona a lista de usuários ao contexto
    if request.user.is_superuser:
        context['users'] = users
    
    # Renderiza o template 'home.html' com o contexto
    return render(request, 'home.html', context)


@login_required
def add(request): #adicionar tarefa
    if request.method == 'POST':
        add_task = Tasks()
        add_task.title_task = request.POST.get('titulo')
        add_task.description_task = request.POST.get('descricao')
        add_task.complete_task = request.POST.get('status')
        add_task.prazo_task = request.POST.get('data')
        add_task.priority_task = request.POST.get('prioridade')
        add_task.user = request.user  # Associe a tarefa ao usuário logado
        add_task.save()
        return redirect('home')
    else:
        return render(request, 'add.html')
    
def edit_task(request, task_id): #adicionar tarefa
    add_task = Tasks.objects.get(id_task=task_id, user=request.user)
    if request.method == 'POST':
        add_task.title_task = request.POST.get('titulo')
        add_task.description_task = request.POST.get('descricao')
        add_task.complete_task = request.POST.get('status')
        add_task.prazo_task = request.POST.get('data')
        add_task.priority_task = request.POST.get('prioridade')
        add_task.user = request.user  # Associe a tarefa ao usuário logado
        add_task.save()
        
        return redirect('home')
    else:
        return render(request, 'editar.html')

@login_required
def update_task(request, task_id): #atualizar tarefa
    task = Tasks.objects.get(id_task=task_id, user=request.user)  # Filtre pela tarefa e pelo usuário
    task.complete_task = not task.complete_task 
    task.save()
    return redirect('home')

@login_required 
def delete_task(request, task_id): #deletar tarefa
    task = Tasks.objects.get(id_task=task_id, user=request.user)  # Filtre pela tarefa e pelo usuário
    task.delete()
    return redirect('home')

def logout(request): #deslogar da conta
    auth_logout(request)
    return redirect('login')

trabalho_py/to_do_list/app/templates/add.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Adicionar Tarefas</title>
    <link rel="stylesheet" href="{% static 'css/add.css' %}">
</head>
<body>
    <header class="header"><h1>Adicionar Tarefas</h1></header>
    <main class="main">
        <div class="container">
            <form action="{% url 'add' %}" method="post"> <!-- form para adicionar uma nova tarefa -->
                {% csrf_token %}    <!-- token de segurança -->
                <input type="text" id="input" name="titulo" placeholder="Título"><br>           <!--campo de texto para o título-->  
                <input type="text" id="input" name="descricao" placeholder="Descrição"><br>     <!--campo de texto para a descrição-->
                <label for="prazo">PRAZO:</label><br>                                               <!--prazo-->
                <input type="date" id="input" name="data" placeholder="Prazo"><br>                                  <!--campo de data para o prazo-->
                <select id="input" name="prioridade">                                           <!--menu suspenso para a prioridade-->
                    <option value="" disabled selected>Prioridade</option>
                    <option value="1">Baixa</option>                                                <!--opções de prioridade-->
                    <option value="2">Média</option>
                    <option value="3">Alta</option>
                </select><br>
                <select id="input" name="status">                                               <!--menu suspenso para a status-->
                    <option value="" disabled selected>Status</option>
                    <option value="1">Pendente</option>                                         <!--opções de status-->
                    <option value="2">Em andamento</option>
                    <option value="3">Concluída</option>
                </select><br>
                <input class="button" type="submit" value="Adicionar">                     <!--botão para adicionar a tarefa-->
            </form>
            <a href="{% url 'home' %}" class="back_button">Voltar</a><!-- link para a página inicial -->
        </div>
    </main>
</body>
</html>

trabalho_py/to_do_list/app/templates/editar.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Adicionar Tarefas</title>
    <link rel="stylesheet" href="{% static 'css/add.css' %}">
</head>
<body>
    <header class="header"><h1>Editar Tarefas</h1></header>
    <main class="main">
        <div class="container">
            <form action="" method="post"> <!-- form para adicionar uma nova tarefa -->
                {% csrf_token %}    <!-- token de segurança -->
                <input type="text" id="input" name="titulo" placeholder="Título"><br>           <!--campo de texto para o título-->  
                <input type="text" id="input" name="descricao" placeholder="Descrição"><br>     <!--campo de texto para a descrição-->
                <label for="prazo">PRAZO:</label><br>                                               <!--prazo-->
                <input type="date" id="input" name="data" placeholder="Prazo"><br>                                  <!--campo de data para o prazo-->
                <select id="input" name="prioridade">                                           <!--menu suspenso para a prioridade-->
                    <option value="" disabled selected>Prioridade</option>
                    <option value="1">Baixa</option>                                                <!--opções de prioridade-->
                    <option value="2">Média</option>
                    <option value="3">Alta</option>
                </select><br>
                <select id="input" name="status">                                               <!--menu suspenso para a status-->
                    <option value="" disabled selected>Status</option>
                    <option value="1">Pendente</option>                                         <!--opções de status-->
                    <option value="2">Em andamento</option>
                    <option value="3">Concluída</option>
                </select><br>
                <input class="button" type="submit" value="Editar">                     <!--botão para adicionar a tarefa-->
            </form>
            <a href="{% url 'home' %}" class="back_button">Voltar</a><!-- link para a página inicial -->
        </div>
    </main>
</body>
</html>

trabalho_py/to_do_list/app/templates/home.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Minha Lista de Tarefas</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
    <header class="header"><h1>Minha Lista de Tarefas</h1></header>
    <main class="main">
        <div class="container">
             <!-- Formulário de filtro -->
             <form class="form" method="get" action="{% url 'home' %}">
                <label class="filtro" for="status">Filtrar por status:</label><br>
                <select name="status" id="status">
                    <option value="">Todos</option>
                    <option value="1">Pendente</option>
                    <option value="2">Em andamento</option>
                    <option value="3">Concluída</option>
                </select><br>
                <!-- se o usuário for um superusuário, exibir o filtro de usuário -->
                {% if user.is_superuser %}
                    <label class="filtro" for="user">Filtrar por usuário:</label><br>
                    <select name="user" id="user">
                        <option value="">Todos</option>
                        {% for u in users %}
                            <option value="{{ u.id }}">{{ u.username }}</option>
                        {% endfor %}
                    </select><br>
                {% endif %}
                <button type="submit" class="button">Filtrar</button>
            </form>
        </div>
            <ul>
                {% for task in tasks %} <!-- tasks é uma variável que contém todas as tarefas do usuário -->
                    <li>
                        <div class="tasks">
                            <form action="{% url 'update_task' task.id_task %}" method="post"> <!-- action é a url que será chamada quando o formulário for submetido -->
                                {% csrf_token %} <!-- token de segurança -->
                                <!-- <input type="checkbox" {% if task.complete_task %}checked{% endif %} onChange="this.form.submit()"> --> <!-- se a tarefa estiver completa, o checkbox estará marcado -->
                            </form>
                            <h3>TAREFA: {{ task.title_task }}</h3><br>                   <!-- título da tarefa -->
                            DESCRIÇÃO: {{ task.description_task }}<br>                   <!-- descrição da tarefa -->
                            PRAZO: {{ task.prazo_task }}<br>                             <!-- prazo da tarefa -->
                            PRIORIDADE: {{ task.get_priority_task_display }}<br>         <!-- prioridade da tarefa -->
                            STATUS: {{task.get_complete_task_display}}<br><br>           <!-- status da tarefa -->
                            {% if user.is_superuser %}
                            {% else %}
                                <a href="{% url 'delete_task' task.id_task %}" class="delete_button">Excluir</a>   <!-- link para excluir a tarefa -->
                                <a href="{% url 'edit_task' task.id_task %}" class="button">Editar</a>      <!-- link para editar a tarefa -->
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <a href="{% url 'add' %}" class="button">Adicionar</a> <!-- link para adicionar uma nova tarefa -->
            <a href="{% url 'logout' %}" class="logout_button">Logout</a>  <!-- link para fazer logout -->
    </main>
</body>
</html>

trabalho_py/to_do_list/app/templates/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    <header class="header"><h1>LOGIN</h1></header>
    <main class="main"></main>
        <div class="container">
            <form method="post">
                {% csrf_token %} <!-- token de segurança -->
                <!-- <label for="username">username:</label> -->                                        <!-- label para o campo de usuário    -->
                <input type="text" id="username" name="username" placeholder="username"><br>            <!-- campo de texto para o usuário    -->
                <!-- <label for="password">password:</label> -->                                        <!-- label para o campo de senha      -->
                <input type="password" id="password" name="password" placeholder="password"><br>        <!-- campo de texto para a senha      -->
                <input type="submit" id="login" value="Login">                                          <!-- botão para submeter o formulário -->
            </form>
        </div>
        <div class="container">
            <p class="registrar">Não tem uma conta?<a href="{% url 'register' %}" class="button">Registre-se aqui</a></p> <!-- link para a página de registro -->
        </div>
    </main>
    <footer class="footer">
        <h3>Melhor sitezinho que ta tendo</h3>
    </footer>
</body>
</html>

trabalho_py/to_do_list/app/templates/register.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Registrar</title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
</head>
<body>
    <header class="header"><h1>Registrar</h1></header>
    <main class="main">
        <form method="post">
            {% csrf_token %} <!-- token de segurança -->
            {{ form.as_p }} <!-- renderiza o formulário de registro -->
            <input type="submit" class="button" value="Registrar"> <!-- botão para submeter o formulário -->
        </form>
    </main>
</body>
</html>